{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwa.fullname" . }}-secret
type: Opaque
stringData:
  DATABASE_USER: {{ .Values.secret.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.DATABASE_PASSWORD | quote }}
  ADMIN_API_KEY: {{ .Values.secret.ADMIN_API_KEY | quote }}
  WEBHOOK_SECRET: {{ .Values.secret.WEBHOOK_SECRET | quote }}
{{- end }}
